# Generated by Django 4.2.10 on 2024-02-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField()),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
