# Generated by Django 4.2.10 on 2024-02-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_alter_cart_pid_alter_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pimage',
            field=models.ImageField(default=0, upload_to='image'),
        ),
    ]
